#!/usr/bin/env node
/* Regenerates fonts.css by embedding the woff2 files as data URIs.
   The Artifact/CSP host blocks external font requests, so the faces have to travel
   inside the stylesheet. Run after `npm pack`-ing the two font packages:

     npm pack @fontsource-variable/archivo @fontsource/ibm-plex-mono
     tar xzf fontsource-variable-archivo-*.tgz -C /tmp/archivo --strip-components=1
     tar xzf fontsource-ibm-plex-mono-*.tgz -C /tmp/plexmono --strip-components=1
     node make-fonts.js /tmp/archivo/files /tmp/plexmono/files
*/

const fs = require('fs');
const path = require('path');

const [archivoDir, plexDir] = process.argv.slice(2);
if (!archivoDir || !plexDir) {
  console.error('usage: node make-fonts.js <archivo files dir> <ibm-plex-mono files dir>');
  process.exit(1);
}

const uri = (file) =>
  'data:font/woff2;base64,' + fs.readFileSync(file).toString('base64');

const faces = [
  {
    family: 'Archivo Variable',
    weight: '100 900',
    stretch: '62% 125%',
    format: 'woff2-variations',
    file: path.join(archivoDir, 'archivo-latin-standard-normal.woff2')
  },
  {
    family: 'IBM Plex Mono',
    weight: '400',
    format: 'woff2',
    file: path.join(plexDir, 'ibm-plex-mono-latin-400-normal.woff2')
  },
  {
    family: 'IBM Plex Mono',
    weight: '500',
    format: 'woff2',
    file: path.join(plexDir, 'ibm-plex-mono-latin-500-normal.woff2')
  }
];

const css = `/* Fonts embedded as data URIs so the app works offline and inside sandboxed hosts.

   Archivo Variable — Copyright 2020 The Archivo Project Authors
   (https://github.com/Omnibus-Type/Archivo), SIL Open Font License 1.1
   IBM Plex Mono — Copyright 2017 IBM Corp. (https://github.com/IBM/plex),
   SIL Open Font License 1.1

   Generated by make-fonts.js — do not edit by hand. */

${faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-display: swap;
  font-weight: ${f.weight};${f.stretch ? `\n  font-stretch: ${f.stretch};` : ''}
  src: url(${uri(f.file)}) format('${f.format}');
}`).join('\n\n')}
`;

fs.writeFileSync(path.join(__dirname, 'fonts.css'), css);
console.log('fonts.css', (Buffer.byteLength(css) / 1024).toFixed(0), 'KB');
